//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongMachTuWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTT
    {
        public int MaPK { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string CachDung { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
