//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongMachTuWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHD { get; set; }
        public Nullable<int> MaPK { get; set; }
        public Nullable<decimal> TienKham { get; set; }
        public Nullable<decimal> TienThuoc { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
