//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongMachTuWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHEN
    {
        public int MaLH { get; set; }
        public int MaNV { get; set; }
        public int MaBN { get; set; }
        public string TenBN { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
