//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongMachTuWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAM()
        {
            this.CTTTs = new HashSet<CTTT>();
            this.HOADONs = new HashSet<HOADON>();
            this.LICHHENs = new HashSet<LICHHEN>();
        }
    
        public int MaPK { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaBN { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string TrieuChung { get; set; }
        public string KetQua { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTT> CTTTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHEN> LICHHENs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
